### ISSUE TITLE
please tag it for 2015

### ISSUE THREAD

**Issue by cordoval** [wmde/Diff#28]

**Comment by thiemowmde** [comment]
What does this mean? Why 2015? Tag what? Are you asking for a 2.0 release?

**Comment by cordoval** [comment]
i am asking for a 1.0.2 if you will, whatever is the minor but shows that we have a new point to avoid requiring unstable packages even when there could be stable tags in between.

**Comment by thiemowmde** [comment]
Which of these changes https://github.com/wmde/Diff/compare/1.0.1...master#diff-7 do you want in a pre-2.0 release? Which of these changes is relevant to you?

**Comment by JeroenDeDauw** [comment]
> to avoid requiring unstable packages

Are you saying you are currently forced to require unstable packages? If so, how?

**Comment by cordoval** [comment]
yes, anything that is the alias branch is unstable. That or when a version requires @dev at the end.

**Comment by JeroenDeDauw** [comment]
I still don't understand what your problem is. The alias branch is 2.0.x, which is inherently unstable as the release has not been made yet. We could make the 2.0 release of course, though at the moment I don't see a lot of reason to do so. And you are talking about 1.0.2, which suggests this is not what you want.

**Comment by cordoval** [comment]
I was talking about 1.0.2 or 1.1.0 just because I assumed wrongly or perhaps rightly that you don't "see a lot of reason to" tag a release.

**Comment by JeroenDeDauw** [comment]
There are no known bugs in the latest stable release (1.0.1), so there are no fixes to put into a new release.

**Comment by cordoval** [comment]
well or enhancements

**Comment by JeroenDeDauw** [comment]
If there are fixes or enhancement, we will provide a new release, as we've always done in the past (see the release notes).

**Comment by cordoval** [comment]
I guess there are two variety of maintaining approaches.
Sometimes one does get features added without a release.

1.0.0 start
you add a feature A
1.1.0
you add another feature B
1.2.0
you add a bugfix and feature C and D
1.3.1
you want to release 2.0.0 with all the features introduced between 1 and 2.

versus

1.0.0
you wait until 10 features get in
you wait more and just bugfix something, thereby creating a release branch for bugfixes 1.0.x
later some months you want to release 2.0.0 with all features
2.0.0 (after a year :baby:)

**Comment by JeroenDeDauw** [comment]
This component follows the former approach. There are exactly 0 fixes and 0 features there are not released yet.

**Comment by cordoval** [comment]
If it is the first approach then what is https://github.com/wmde/Diff/compare/1.0.1...master#diff-7 ? unless I got the terminology wrong.

**Comment by JeroenDeDauw** [comment]
These are either internal or infrastructure changes that are not interesting to users of the library, or breaking changes (ie removal of an interface) that do not yet justify a mayor release.

**Comment by sstok** [comment]
I think I see what the problem is, the readme tells to use `"2.0.*"` but there is no tagged version with 2.0 (even not an 2.0.0-alpha1) so you're suggesting to install an unstable version! (because the readme tells you to).

But you can't install a dev version unless minimum-stability is set to dev or using the `@dev` annotation at the end of the constraint.

Second to this its not save to rely on a dev version in alpha stage, if something changes you have no version to target for the current moment and you can't also point a minimum version like `~2.0,>=2.0.0-alpha1`! Which is why its best to tag a new alpha/beta release whenever something changes in an backward incompatible way within an unstable version.

But in this case because there is on actual 2.0 version planned the branch-alias should point a minor version NOT a major. Something like `1.2.x-dev` so that using `~1.0` will also use the 1.2 version whenever that comes out.

Or put differently: *The branch-alias should point to what should be next none-breaking version of the target branch.* When your current version is `1.0.0` then the next version would be `1.1.0` so your branch alias is `1.1.x-dev`, when 1.1.0 is finally released the branch alias is updated to `1.2.x-dev`.

I hope this clarifies it :+1: It took me also some time to understand this construct :smile:

**Comment by sstok** [comment]
Btw, would you consider changing the license of this library to **L**GPL? Because GPL is very restrictive, it requires that the using application (and other libraries) also are under GPL.
While LGPL does not have restriction, besides that its still the same.
